### ISSUE TITLE
[REQ] Support MiniAdmin & BasicAdmin 

### ISSUE THREAD

**Issue by crashzk** [ShiNxz/CSS-Panel#2]
Can we expect support for the [MiniAdmin](https://github.com/partiusfabaa/cs2-MiniAdmin) and [BasicAdmin](https://github.com/Hackmastr/css-basic-admin) plugins?

Or will it be exclusive to [SimpleAdmin](https://github.com/daffyyyy/CS2-SimpleAdmin)?

**Comment by ShiNxz** [comment]
I've decided to fork the SimpleAdmin into an exclusive plugin for the panel, kind of like SourceBans team did.
https://github.com/ShiNxz/CSS-Plugin/releases
I think it will be the best as the panel needs to sync with the game servers and we need to add more features that the plugin doesn't support at the moment.

**Comment by crashzk** [comment]
> I've decided to fork the SimpleAdmin into an exclusive plugin for the panel, kind of like SourceBans team did. https://github.com/ShiNxz/CSS-Plugin/releases I think it will be the best as the panel needs to sync with the game servers and we need to add more features that the plugin doesn't support at the moment.

I understand, in this case your version will be a mirror of SimpleAdmin? Or can we expect improvements and new features in your version?

And will support only be for your version of SimpleAdmin or can we use daffyyyy's version?

**Comment by crashzk** [comment]
Note, I believe you can create a project for the CSS Panel, more organized to leave all repositories there, and thus something exclusive to the plugin, something like SourceMod, SourceBans++ and Levels Ranks, anyway, here's a suggestion.

**Comment by ShiNxz** [comment]
> > I've decided to fork the SimpleAdmin into an exclusive plugin for the panel, kind of like SourceBans team did. https://github.com/ShiNxz/CSS-Plugin/releases I think it will be the best as the panel needs to sync with the game servers and we need to add more features that the plugin doesn't support at the moment.
> 
> I understand, in this case your version will be a mirror of SimpleAdmin? Or can we expect improvements and new features in your version?
> 
> And will support only be for your version of SimpleAdmin or can we use daffyyyy's version?

My plan is making new features, such as server groups and roles with pre assinged flags, in the db itself, and much more hopefully.
The panel will support both versions but obviously will contain less features, currently the only changes i made are fixing the pterodactyl ip issue (0.0.0.0) and adding a new console command for rcon, so the panel will be able to pull much more information about the server and the players.
And the panel checks if the server is using our version or daffy's version and pulls the information based on the plugin, but the query command as I said pulls much more information so the server and players table will show much more data.
And its only the first step.

**Comment by crashzk** [comment]
Perfect, that would be it for now.

I'll be testing the CSS Panel and its features, I'll get in touch with anything, thanks again!
