### ISSUE TITLE
[REQ] Support for Reporting Players & Appealing Bans/Comms

### ISSUE THREAD

**Issue by crashzk** [ShiNxz/CSS-Panel#3]
Page for reporting players and another page for players banned or with blocked comms to appeal to have the punishments removed.

I believe that a connection to discord (Webhook) would be perfect. After the order is placed on the website, it is sent to a discord channel that has been configured.

This option would only be visible on the website, in the menu if you configure these options in this case, configure the webhook link, etc.

**Comment by ShiNxz** [comment]
Hey, that's a good idea and planned for the future panel modules, meaning it wont be part of the default panel behavior, but something you will be able to enable easily through the admin panel, in the future.
